title: Pokémon Go Norwich
description: ''
timezone: Europe/London

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

sass:
  sass_dir: assets/css
